package:
    name:           yii2-thememanager
    namespace:      hiqdev\thememanager
    label:          ThemeManager
    title:          Theme Manager for Yii2
    type:           yii2-extension
    keywords:       theme, manager, extension, yii2
    year:           2015
    description:    Theme Manager with auto loading from extension, choose and setup widgets

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
