package:
    type:           yii2-extension
    name:           yii2-thememanager
    title:          Theme Manager for Yii2
    headline:       Yii2 Theme Manager
    keywords:       yii2, theme, manager
    namespace:      hiqdev\thememanager
    description:    Theme Manager with auto loading, choose and setup widgets

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
