parent:
    github:         hiqdev/hidev-config

package:
    name:           yii2-thememanager
    namespace:      hiqdev\thememanager
    label:          ThemeManager
    title:          Theme Manager for Yii2
    type:           yii2-extension
    keywords:       theme, manager, extension, yii2
    description:    Theme Manager with auto loading from extension, choose and setup widgets
    year:           2015

composer.json:
    require:
        hiqdev/yii2-pluginmanager:      "*@dev"
